server:
  port: 8080
spring:
  application:
    name: multi-datasource
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    write:
      # spring boot 2.0之前使用这个url
      # url: jdbc:mysql://localhost:3306/wx?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
      jdbc-url: jdbc:mysql://localhost:3306/wx?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
      username: admin
      password: admin
    read:
      # spring boot 2.0之前使用这个url
      # url: jdbc:mysql://localhost:3306/wx?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
      jdbc-url: jdbc:mysql://localhost:3306/wx?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
      username: admin
      password: admin
    driver-class-name: com.mysql.jdbc.Driver
    continue-on-error: true
